# Generated by Django 4.1.5 on 2024-03-21 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finflow_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commMemberStoreGroup', models.CharField(max_length=255, verbose_name='공동 회원 매장 그룹')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '공동 회원 매장 그룹',
                'verbose_name_plural': '공동 회원 매장 그룹들',
                'db_table': 'store_group',
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resCardCompany', models.CharField(max_length=100, verbose_name='카드 회사')),
                ('resTotalAmount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='총 금액')),
                ('resTotalCount', models.IntegerField(verbose_name='총 거래 횟수')),
                ('resUsedAmount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='사용 금액')),
                ('resCount', models.IntegerField(verbose_name='사용 건수')),
                ('resCancelAmount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='취소 금액')),
                ('resCancelCount', models.IntegerField(verbose_name='취소 건수')),
                ('store_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finflow_control.storegroup', verbose_name='매장 그룹')),
            ],
            options={
                'verbose_name': '거래 기록',
                'verbose_name_plural': '거래 기록들',
                'db_table': 'transaction_history',
            },
        ),
        migrations.CreateModel(
            name='ApprovalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resType', models.CharField(max_length=50, verbose_name='거래 유형')),
                ('resAccountTrDate', models.DateField(verbose_name='거래 날짜')),
                ('resAccountTrTime', models.TimeField(verbose_name='거래 시간')),
                ('resCardCompany', models.CharField(max_length=100, verbose_name='카드 회사')),
                ('resCardName', models.CharField(blank=True, max_length=100, verbose_name='카드 명')),
                ('resCardNo', models.CharField(max_length=100, verbose_name='카드 번호')),
                ('resApprovalNo', models.CharField(blank=True, max_length=100, verbose_name='승인 번호')),
                ('resUsedAmount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='사용 금액')),
                ('resInstallmentMonth', models.CharField(max_length=50, verbose_name='할부 개월')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_details', to='finflow_control.transactionhistory', verbose_name='거래 기록')),
            ],
            options={
                'verbose_name': '승인 상세',
                'verbose_name_plural': '승인 상세들',
                'db_table': 'approval_detail',
            },
        ),
    ]
