# Generated by Django 4.1.5 on 2024-03-21 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finflow_control', '0002_storegroup_transactionhistory_approvaldetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvaldetail',
            options={'verbose_name': '거래처 승인 상세', 'verbose_name_plural': '거래처 승인 상세들'},
        ),
        migrations.AlterModelOptions(
            name='storegroup',
            options={'verbose_name': '서비스 이용 거래처 리스트', 'verbose_name_plural': '서비스 이용 거래처 리스트'},
        ),
        migrations.AlterModelOptions(
            name='transactionhistory',
            options={'verbose_name': '거래처 거래 기록', 'verbose_name_plural': '거래처 거래 기록들'},
        ),
        migrations.AlterModelTable(
            name='approvaldetail',
            table='FinFlow_Approval_Detail_TB',
        ),
        migrations.AlterModelTable(
            name='storegroup',
            table='FinFlow_Store_Group_TB',
        ),
        migrations.AlterModelTable(
            name='transactionhistory',
            table='FinFlow_Transaction_History_TB',
        ),
        migrations.CreateModel(
            name='ApprovalCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateField(verbose_name='승인 Request 날짜')),
                ('approval_check', models.BooleanField(default=False, verbose_name='승인 Request 여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '승인체크',
                'verbose_name_plural': '승인체크',
                'db_table': 'FinFlow_Approval_Check_TB',
            },
        ),
    ]
