# Generated by Django 3.2 on 2024-03-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_kind',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='은행명'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_number',
            field=models.CharField(blank=True, default='', max_length=20, unique=True, verbose_name='통장번호'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_pw',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='통장비밀번호'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_ComName',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='사업자명'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='사업자주소'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_biznum',
            field=models.CharField(blank=True, default='', max_length=10, unique=True, verbose_name='사업자번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_user_id',
            field=models.CharField(blank=True, default='', max_length=20, unique=True, verbose_name='뱅크아이디'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_user_pw',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='뱅크비밀번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='card_user_id',
            field=models.CharField(blank=True, default='', max_length=20, unique=True, verbose_name='카드아이디'),
        ),
        migrations.AlterField(
            model_name='user',
            name='card_user_pw',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='카드비밀번호'),
        ),
    ]
