# Generated by Django 4.1.5 on 2024-03-20 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240315_1139'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='FinFlow_User_TB',
        ),
    ]
