# Generated by Django 4.1.5 on 2024-03-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='통장번호'),
        ),
    ]
