# Generated by Django 4.1.5 on 2024-03-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_bank_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_user_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='뱅크아이디'),
        ),
        migrations.AlterField(
            model_name='user',
            name='card_user_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='카드아이디'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_biznum',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='사업자번호'),
        ),
    ]
